/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaMenu;

import Cadastro.NovoCadastro;
import javax.swing.JOptionPane;

/**
 *
 * @author Raiane Campos
 */
public class MenuNovoCadastro extends javax.swing.JFrame {

    public MenuNovoCadastro() {
        initComponents();

    }

    Cadastro.NovoCadastro cadastro = new Cadastro.NovoCadastro();
    MenuPrincipal Principal = new MenuPrincipal();
    int matricula = 0;
    private int matricula(){
    this.matricula++;
    return matricula;
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        laNome = new javax.swing.JLabel();
        laEndereço = new javax.swing.JLabel();
        laCpf = new javax.swing.JLabel();
        laTel = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        txEndereco = new javax.swing.JTextField();
        txCpf = new javax.swing.JTextField();
        txTel = new javax.swing.JTextField();
        txBairro = new javax.swing.JTextField();
        txCidade = new javax.swing.JTextField();
        laCidade = new javax.swing.JLabel();
        laBairro = new javax.swing.JLabel();
        coEstados = new javax.swing.JComboBox();
        laEmail = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        boConfirma = new javax.swing.JButton();
        boCancela = new javax.swing.JButton();
        laMatricula = new javax.swing.JLabel();
        laNumMat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(685, 628));

        laNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laNome.setForeground(new java.awt.Color(51, 204, 255));
        laNome.setText("Nome");

        laEndereço.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laEndereço.setForeground(new java.awt.Color(51, 204, 255));
        laEndereço.setText("Endereço");

        laCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laCpf.setForeground(new java.awt.Color(51, 204, 255));
        laCpf.setText("CPF");

        laTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laTel.setForeground(new java.awt.Color(51, 204, 255));
        laTel.setText("Telefone");

        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });

        txEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEnderecoActionPerformed(evt);
            }
        });

        txCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCpfActionPerformed(evt);
            }
        });

        txTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelActionPerformed(evt);
            }
        });

        txBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBairroActionPerformed(evt);
            }
        });

        txCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCidadeActionPerformed(evt);
            }
        });

        laCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laCidade.setForeground(new java.awt.Color(0, 204, 255));
        laCidade.setText("Cidade");

        laBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laBairro.setForeground(new java.awt.Color(0, 204, 255));
        laBairro.setText("Bairro");

        coEstados.setForeground(new java.awt.Color(0, 204, 255));
        coEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        laEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laEmail.setForeground(new java.awt.Color(0, 204, 255));
        laEmail.setText("Email");

        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });

        boConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/023.png"))); // NOI18N
        boConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boConfirmaActionPerformed(evt);
            }
        });

        boCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/020.png"))); // NOI18N
        boCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boCancelaActionPerformed(evt);
            }
        });

        laMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laMatricula.setForeground(new java.awt.Color(0, 204, 255));
        laMatricula.setText("Matricula");

        laNumMat.setText("Numero Cadastro");
        laNumMat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                laNumMatAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(boCancela)
                        .addGap(85, 85, 85)
                        .addComponent(boConfirma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laEndereço)
                            .addComponent(laEmail)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(txBairro))
                                    .addComponent(laBairro))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(laCidade)
                                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(coEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(laCpf)
                                .addGap(173, 173, 173)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(laTel)
                                        .addGap(173, 173, 173))
                                    .addComponent(txTel, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                            .addComponent(txEndereco)
                            .addComponent(laNome)
                            .addComponent(txNome))))
                .addGap(18, 99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(laMatricula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(laNumMat)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laNumMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(laNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laEndereço)
                .addGap(18, 18, 18)
                .addComponent(txEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laCidade)
                    .addComponent(laBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(laCpf)
                                    .addComponent(laTel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addComponent(laEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boConfirma)
                    .addComponent(boCancela))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBairroActionPerformed

    }//GEN-LAST:event_txBairroActionPerformed

    private void txTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelActionPerformed

    }//GEN-LAST:event_txTelActionPerformed

    private void boCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boCancelaActionPerformed
        this.dispose();
        Principal.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_boCancelaActionPerformed

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed

    }//GEN-LAST:event_txNomeActionPerformed

    private void txEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEnderecoActionPerformed

    }//GEN-LAST:event_txEnderecoActionPerformed

    private void txCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCidadeActionPerformed

    }//GEN-LAST:event_txCidadeActionPerformed

    private void txCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCpfActionPerformed

    }//GEN-LAST:event_txCpfActionPerformed

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed

    }//GEN-LAST:event_txEmailActionPerformed

    private void boConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boConfirmaActionPerformed
        cadastro.setBairro(txBairro.getText());
        cadastro.setTelefone(txTel.getText());
        cadastro.setNome(txNome.getText());
        cadastro.setEndereco(txEndereco.getText());
        cadastro.setCidade(txCidade.getText());
        cadastro.setCpf(txCpf.getText());
        cadastro.setEmail(txEmail.getText());
        cadastro.addCadastro();
        JOptionPane.showMessageDialog(null, "Cadastro Concluido");
        this.dispose();
        Principal.setVisible(true);System.out.println("cada"+matricula);
    }//GEN-LAST:event_boConfirmaActionPerformed

    private void laNumMatAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_laNumMatAncestorMoved
//        laNumMat.setText(""+(cadastro.matricula + 1) );
        
    }//GEN-LAST:event_laNumMatAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNovoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boCancela;
    private javax.swing.JButton boConfirma;
    private javax.swing.JComboBox coEstados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laBairro;
    private javax.swing.JLabel laCidade;
    private javax.swing.JLabel laCpf;
    private javax.swing.JLabel laEmail;
    private javax.swing.JLabel laEndereço;
    private javax.swing.JLabel laMatricula;
    private javax.swing.JLabel laNome;
    private javax.swing.JLabel laNumMat;
    private javax.swing.JLabel laTel;
    private javax.swing.JTextField txBairro;
    private javax.swing.JTextField txCidade;
    private javax.swing.JTextField txCpf;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txEndereco;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txTel;
    // End of variables declaration//GEN-END:variables
}
