/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaMenu;

import Cadastro.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Raiane Campos
 */
public class MenuPesquisa extends javax.swing.JFrame {

    public MenuPesquisa() {
        initComponents();

    }

    Cadastro.NovoCadastro cadastro = new Cadastro.NovoCadastro();
    Cadastro.TelaPrincipal telaMain = new Cadastro.TelaPrincipal();
    MenuPrincipal principal = new MenuPrincipal();
     MenuMatricula telaMatricula = new MenuMatricula();
    
    int matricula = 0;

    private int matricula() {
        this.matricula++;
        return matricula;
    }

    ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diMatricula = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        laMatricula = new javax.swing.JLabel();
        laNumMat = new javax.swing.JLabel();
        laNome1 = new javax.swing.JLabel();
        laTel1 = new javax.swing.JLabel();
        laCpf1 = new javax.swing.JLabel();
        laEndereço1 = new javax.swing.JLabel();
        laBairro1 = new javax.swing.JLabel();
        laCidade1 = new javax.swing.JLabel();
        laEmail1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        diMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        diMatricula.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                diMatriculaAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        javax.swing.GroupLayout diMatriculaLayout = new javax.swing.GroupLayout(diMatricula.getContentPane());
        diMatricula.getContentPane().setLayout(diMatriculaLayout);
        diMatriculaLayout.setHorizontalGroup(
            diMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        diMatriculaLayout.setVerticalGroup(
            diMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(685, 628));

        laMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laMatricula.setForeground(new java.awt.Color(0, 204, 255));
        laMatricula.setText("Matricula");

        laNumMat.setText("Numero Cadastro");
        laNumMat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                laNumMatAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        laNome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laNome1.setText("Nome");
        laNome1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                laNome1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        laTel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laTel1.setText("Telefone");

        laCpf1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laCpf1.setText("CPF");

        laEndereço1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laEndereço1.setText("Endereço");

        laBairro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laBairro1.setText("Bairro");

        laCidade1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laCidade1.setText("Cidade");

        laEmail1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laEmail1.setText("Email");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/017.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(257, 257, 257))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laEmail1)
                    .addComponent(laCpf1)
                    .addComponent(laTel1)
                    .addComponent(laNome1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laMatricula)
                        .addGap(18, 18, 18)
                        .addComponent(laNumMat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(laEndereço1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(laBairro1)
                        .addGap(224, 224, 224)
                        .addComponent(laCidade1)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laMatricula)
                    .addComponent(laNumMat))
                .addGap(18, 18, 18)
                .addComponent(laNome1)
                .addGap(18, 18, 18)
                .addComponent(laTel1)
                .addGap(18, 18, 18)
                .addComponent(laCpf1)
                .addGap(18, 18, 18)
                .addComponent(laEndereço1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laBairro1)
                    .addComponent(laCidade1))
                .addGap(18, 18, 18)
                .addComponent(laEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laNumMatAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_laNumMatAncestorMoved
        laNumMat.setText("" + (telaMain.matricula));

    }//GEN-LAST:event_laNumMatAncestorMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void laNome1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_laNome1AncestorMoved
        int mat =telaMatricula.numMat;
        laBairro1.setText("Bairro: " + cadastro.getBairro(mat));
        laCidade1.setText("Cidade: " + cadastro.getCidade(mat));
        laCpf1.setText("CPF: " + cadastro.getCpf(mat));
        laEmail1.setText("Email: " + cadastro.getEmail(mat));
        laEndereço1.setText("Endereço: " + cadastro.getEndereco(mat));
        laNome1.setText("Nome: " + cadastro.getNome(mat));
        laTel1.setText("Telefone: " + cadastro.getTelefone(mat));
    }//GEN-LAST:event_laNome1AncestorMoved

    private void diMatriculaAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_diMatriculaAncestorMoved

    }//GEN-LAST:event_diMatriculaAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
               new MenuPesquisa().setVisible(true);
                 

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog diMatricula;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel laBairro1;
    private javax.swing.JLabel laCidade1;
    private javax.swing.JLabel laCpf1;
    private javax.swing.JLabel laEmail1;
    private javax.swing.JLabel laEndereço1;
    private javax.swing.JLabel laMatricula;
    private javax.swing.JLabel laNome1;
    private javax.swing.JLabel laNumMat;
    private javax.swing.JLabel laTel1;
    // End of variables declaration//GEN-END:variables
}
